### ISSUE TITLE
Maybe implement an `.at_least` parameter

### ISSUE THREAD

**Issue by chrislim5** [DavisVaughan/slider#106]
Would it be possible to allow for intermediate values less than a fully complete windows to be computed in the slide function? For example, if I have a window size of 10 observations, I would like to be able to calculate the rolling mean if there are at least 5 observations, but not fewer.

**Comment by DavisVaughan** [comment]
I'm not completely sold that this should be part of the API, but I see how it can be useful.

In the meantime, you can use the lower level `hop_vec()` function to build something that accomplishes what you want. No guarantees that this captures all of the edge cases, but it seems to work pretty well.

``` r
library(slider)
library(vctrs)

slide_dbl_at_least <- function(.x, .f, ..., .before = 0L, .after = 0L, .at_least = 5L) {
  size <- vec_size(.x)
  i <- seq_len(size)
  
  # Compute the start and stop locations of each window
  starts <- i - .before
  stops <- i + .after
  
  # Make sure to "clamp" them to the start and end of the sequence
  starts <- pmax(starts, 1L)
  stops <- pmin(stops, size)
  
  # Compute the number of values in each range
  n_values <- stops - starts + 1L
  
  indicator_compute <- n_values >= .at_least
  
  # Trim starts and stops to only valid ones
  starts <- starts[indicator_compute]
  stops <- stops[indicator_compute]
  
  # Initialize an output vector with the full result size
  # (locations where we don't compute a value get an `NA`)
  out <- vec_init(double(), n = size)
  
  # Compute the rolling mean where applicable
  results <- hop_vec(
    .x = .x, 
    .starts = starts, 
    .stops = stops, 
    .f = .f, 
    ..., 
    .ptype = double()
  )
  
  # Assign the results into the larger vector of `NA`s
  out <- vec_assign(out, indicator_compute, results)
  
  out
}

slide_dbl_at_least(1:20, mean, .before = 9, .at_least = 5)
#>  [1]   NA   NA   NA   NA  3.0  3.5  4.0  4.5  5.0  5.5  6.5  7.5  8.5  9.5 10.5
#> [16] 11.5 12.5 13.5 14.5 15.5

slide_dbl_at_least(1:20, mean, .before = 2, .after = 2, .at_least = 5)
#>  [1] NA NA  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 NA NA
```

<sup>Created on 2020-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by chrislim5** [comment]
Thanks! Much appreciated.

**Comment by DavisVaughan** [comment]
I have prototyped this out and have decided that the added complexity it adds to the C code and the overall API likely outweigh the benefits. If multiple other people ask for this in the future, we can revisit.
