### ISSUE TITLE
simple math

### ISSUE THREAD

**Issue by under-score** [DavisVaughan/slider#107]

**Comment by DavisVaughan** [comment]
I think you noticed this, but the calculation is based on the current element + the 2 before it. So it would have been `mean(c(.5, 2, 0))` which was giving the correct value

**Comment by under-score** [comment]
> Am 04.06.2020 um 14:20 schrieb Davis Vaughan <notifications@github.com>:
> I think you noticed this, but the calculation is based on the current element + the 2 before it. So it would have been mean(c(.5, 2, 0)) which was giving the correct value
> 

thank you, already noticed that.

**Comment by under-score** [comment]
great work, thank you.

Maybe you add to the documentation that negative values are allowed in .before
to shift the whole window downwards

**Comment by DavisVaughan** [comment]
It is there in the documentation for `.before` in `?slide_dbl`

> The number of values before or after the current element to include in the sliding window. Set to Inf to select all elements before or after the current element. Negative values are allowed, which allows you to "look forward" from the current element if used as the .before value, or "look backwards" if used as .after.

**Comment by under-score** [comment]
> Am 04.06.2020 um 16:04 schrieb Davis Vaughan <notifications@github.com>:
> It is there in the documentation for .before in ?slide_dbl
> 

exactly. I looked only at the CRAN doc...
