### ISSUE TITLE
Tsibble's Stretch Equivalent 

### ISSUE THREAD

**Issue by Michael-Sheppard** [DavisVaughan/slider#108]
Can more clear and accessible documentation as to what the slider equivalent of tsibble's stretch please be provided? I see their current documentation recommends to use slider, but its not clear to me or anyone else what the equivalent of some of the other functions are. It appears they exist, but there is nothing that I can find...

**Comment by DavisVaughan** [comment]
Generally this is accomplished with `slide(.before = Inf)`

``` r
library(tsibble)
library(slider)
#> 
#> Attaching package: 'slider'
#> The following objects are masked from 'package:tsibble':
#> 
#>     pslide, pslide_chr, pslide_dbl, pslide_dfc, pslide_dfr, pslide_int,
#>     pslide_lgl, slide, slide_chr, slide_dbl, slide_dfc, slide_dfr,
#>     slide_int, slide_lgl, slide2, slide2_chr, slide2_dbl, slide2_dfc,
#>     slide2_dfr, slide2_int, slide2_lgl

stretch(1:5, ~.x, .step = 2)
#> Warning: `stretch()` is deprecated as of tsibble 0.9.0.
#> Please use `slider::slide()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] NA
#> 
#> [[3]]
#> [1] 1 2 3
#> 
#> [[4]]
#> [1] NA
#> 
#> [[5]]
#> [1] 1 2 3 4 5

slide(1:5, ~.x, .before = Inf, .step = 2)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> [1] 1 2 3
#> 
#> [[4]]
#> NULL
#> 
#> [[5]]
#> [1] 1 2 3 4 5
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think I want to explicitly compare to tsibble (or zoo for that matter) in the examples, but `?slide` does have a "Cumulative sliding" example section that talks about how this works
