### ISSUE TITLE
Feature Request: Loop in slide_* functions

### ISSUE THREAD

**Issue by AlanFeder** [DavisVaughan/slider#117]
Hi,

I have a feature suggestion for the slide functions.

I would find it useful if there was an ability to allow one to "loop" easily over a period.  

For example, if one had a data set of the average temperatures of a location for each day of the year (Day 1, Day 2, ..., Day 365) (ignore leap year for the moment), It would be easy to calculate "What is the 5 day average temperature from July 7 through July 11" using slide.  However, it would be less easy to calculate "What is the 5 day average temperature from December 29 through January 2" using slide.

If this is easy to implement, I think it could add possible uses to the package.

Thank you!

**Comment by DavisVaughan** [comment]
I'm not sure what you mean. You can do a 5 day average across year boundaries without doing anything special

``` r
library(slider)

start <- as.Date("2008-12-29")
stop <- as.Date("2009-01-06")

i <- seq(start, stop, by = "1 day")
x <- runif(length(i))

slide_index(i, i, identity, .before = 4)
#> [[1]]
#> [1] "2008-12-29"
#> 
#> [[2]]
#> [1] "2008-12-29" "2008-12-30"
#> 
#> [[3]]
#> [1] "2008-12-29" "2008-12-30" "2008-12-31"
#> 
#> [[4]]
#> [1] "2008-12-29" "2008-12-30" "2008-12-31" "2009-01-01"
#> 
#> [[5]]
#> [1] "2008-12-29" "2008-12-30" "2008-12-31" "2009-01-01" "2009-01-02"
#> 
#> [[6]]
#> [1] "2008-12-30" "2008-12-31" "2009-01-01" "2009-01-02" "2009-01-03"
#> 
#> [[7]]
#> [1] "2008-12-31" "2009-01-01" "2009-01-02" "2009-01-03" "2009-01-04"
#> 
#> [[8]]
#> [1] "2009-01-01" "2009-01-02" "2009-01-03" "2009-01-04" "2009-01-05"
#> 
#> [[9]]
#> [1] "2009-01-02" "2009-01-03" "2009-01-04" "2009-01-05" "2009-01-06"

# rolling 5 day average
slide_index_dbl(x, i, mean, .before = 4)
#> [1] 0.7484956 0.4081665 0.3791450 0.2993971 0.3923268 0.3886595 0.4274407
#> [8] 0.4027697 0.4872244
```

<sup>Created on 2020-08-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by AlanFeder** [comment]
My motivation had been that I was sent data that was aggregated over 20
years at the date level (avg of 2000-2019 for Jan 1, avg of 2000-2019 for
Jan 2, etc...) , and I just wanted to smooth (3 days before, 3 days after).

In the end, I "solved" this by repeating the data 3 times back-to-back,
using slide to get the mean, and then dropping all but the middle year.

(for example, if I was doing it for days of the week, I might have data for
Sunday through Saturday, but I might want the Sunday "average" to be Sat,
Sun, & Mon). (obviously this use case doesn't make much sense -- but its
easier as a reprex)

``` r
library(slider)
library(dplyr)
library(tidyr)


df1 <- tibble(day_of_week = 1:7,
              avg_temp = c(68, 69, 70, 71, 70, 69, 68),
              years = "2000-2019")

df1 %>%
  mutate(smoothed_avg_temp = slide_dbl(avg_temp, mean, .before = 1, .after
= 1, .complete = TRUE))
#> # A tibble: 7 x 4
#>   day_of_week avg_temp years     smoothed_avg_temp
#>         <int>    <dbl> <chr>                 <dbl>
#> 1           1       68 2000-2019              NA
#> 2           2       69 2000-2019              69
#> 3           3       70 2000-2019              70
#> 4           4       71 2000-2019              70.3
#> 5           5       70 2000-2019              70
#> 6           6       69 2000-2019              69
#> 7           7       68 2000-2019              NA

crossing(id = 1:3, df1) %>%
  mutate(smoothed_avg_temp = slide_dbl(avg_temp, mean, .before = 1, .after
= 1, .complete = TRUE)) %>%
  filter(id == 2) %>%
  select(-id)
#> # A tibble: 7 x 4
#>   day_of_week avg_temp years     smoothed_avg_temp
#>         <int>    <dbl> <chr>                 <dbl>
#> 1           1       68 2000-2019              68.3
#> 2           2       69 2000-2019              69
#> 3           3       70 2000-2019              70
#> 4           4       71 2000-2019              70.3
#> 5           5       70 2000-2019              70
#> 6           6       69 2000-2019              69
#> 7           7       68 2000-2019              68.3
```

<sup>Created on 2020-09-01 by the [reprex package](
https://reprex.tidyverse.org) (v0.3.0)</sup>


Anyway, I was able to figure out a back -handed way of solving it -- but I
feel like I've run into cyclical data in the past. I could imagine it being
done with an argument ".loop = TRUE" or something
