### ISSUE TITLE
slider_period error: invalid index: out of bounds

### ISSUE THREAD

**Issue by akarlinsky** [DavisVaughan/slider#122]
These 3 slide calls should be equivariant to compute a weekly (7 day) rolling average:
```r
library(tidyverse)
example_data <- tibble::tribble(
         ~date, ~tests, ~positive_tests, ~positive_tests2, ~day,
  "11/03/2020",   388L,             45L,              45L,   4L,
  "12/03/2020",   666L,             45L,              45L,   5L,
  "13/03/2020",   765L,             38L,              38L,   6L,
  "14/03/2020",   762L,             50L,              50L,   7L,
  "15/03/2020",  1241L,            103L,             103L,   1L,
  "16/03/2020",  1620L,            129L,             129L,   2L,
  "17/03/2020",  1734L,            152L,             152L,   3L,
  "18/03/2020",  2291L,            211L,             211L,   4L,
  "19/03/2020",  2498L,            205L,             205L,   5L,
  "20/03/2020",  2040L,            217L,             217L,   6L,
  "21/03/2020",  1899L,            235L,             235L,   7L,
  "22/03/2020",  4240L,            392L,             392L,   1L,
  "23/03/2020",  4038L,            510L,             510L,   2L,
  "24/03/2020",  5340L,            471L,             471L,   3L,
  "25/03/2020",  6107L,            625L,             625L,   4L,
  "26/03/2020",  7219L,            652L,             652L,   5L,
  "27/03/2020",  6470L,            635L,             635L,   6L,
  "28/03/2020",  6369L,            568L,             568L,   7L,
  "29/03/2020",  5965L,            569L,             569L,   1L,
  "30/03/2020",  6935L,            763L,             763L,   2L
  )

example_data %>% 
  select(date, tests, positive_tests) %>% 
  pivot_longer(-date, names_to = "type", values_to = "value") %>% 
  group_by(type) %>%   
  mutate(value_ma = tsibble::slide_dbl(value, mean, na.rm = TRUE, .size = 7, .align = "center"),
         value_ma2 = slider::slide_dbl(value, mean, na.rm=T, .before = 3, .after = 3, .complete = TRUE),
         value_ma3 = slider::slide_period_dbl(.x=value, .i=date, .period = "week", .f=mean, na.rm=T))

```

and value_ma1 and value_ma2 indedd are.
but value_ma3 exits with an error:
`Error: Invalid index: out of bounds`

The trackback is:

> 22.
> `[[.vctrs_list_of`(rows, i)
> 21.
> rows[[i]]
> 20.
> vec_size(rows[[i]])
> 19.
> (function (e) { local_call_step(dots = dots, .index = i, .fn = "mutate", .dot_data = inherits(e, "rlang_error_data_pronoun_not_found")) ...
> 18.
> signalCondition(cnd)
> 17.
> signal_abort(cnd)
> 16.
> (function (message = NULL, class = NULL, ..., trace = NULL, parent = NULL, .subclass) { validate_signal_args(.subclass) ...
> 15.
> exec(abort, class = class, !!!.envir)
> 14.
> abort_glue(character(0), list(x_size = 31L), "dplyr:::mutate_incompatible_size")
> 13.
> mask$eval_all_mutate(dots[[i]])
> 12.
> withCallingHandlers({ for (i in seq_along(dots)) { not_named <- (is.null(dots_names) || dots_names[i] == "") ...
> 11.
> mutate_cols(.data, ...)
> 10.
> mutate.data.frame(., value_ma = slide_dbl(value, mean, na.rm = TRUE, .size = 7, .align = "center"), value_ma2 = slider::slide_dbl(value, mean, na.rm = T, .before = 3, .after = 3), value_ma3 = slider::slide_period_dbl(.x = value, .i = date, .period = "week", .f = mean, na.rm = T))
> 9.
> mutate(., value_ma = slide_dbl(value, mean, na.rm = TRUE, .size = 7, .align = "center"), value_ma2 = slider::slide_dbl(value, mean, na.rm = T, .before = 3, .after = 3), value_ma3 = slider::slide_period_dbl(.x = value, .i = date, .period = "week", .f = mean, na.rm = T))
> 8.
> function_list[[k]](value)
> 7.
> withVisible(function_list[[k]](value))
> 6.
> freduce(value, `_function_list`)
> 5.
> `_fseq`(`_lhs`)
> 4.
> eval(quote(`_fseq`(`_lhs`)), env, env)
> 3.
> eval(quote(`_fseq`(`_lhs`)), env, env)
> 2.
> withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 1.
> covid_lab_per_day %>% select(date, tests, positive_tests) %>% pivot_longer(-date, names_to = "type", values_to = "value") %>% mutate(value_ma = slide_dbl(value, mean, na.rm = TRUE, .size = 7, .align =

**Comment by DavisVaughan** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by akarlinsky** [comment]
Sorry for that, updated it with reprex.

**Comment by DavisVaughan** [comment]
Oh, I think you've misunderstood how `slide_period()` and its variants work.

The way you are using it here, it will break up the data into four 7-day periods, will compute the mean on the data in those 4 chunks, and will only return those four results. So the length isn't right for usage in a dplyr `mutate()`.

Here is proof that it is working, you can see what it is iterating over by using `slide_period()` and just returning the data itself.

``` r
library(tidyverse)
#> Warning: package 'tidyr' was built under R version 4.0.2

example_data <- tibble::tribble(
  ~date, ~tests, ~positive_tests, ~positive_tests2, ~day,
  "11/03/2020",   388L,             45L,              45L,   4L,
  "12/03/2020",   666L,             45L,              45L,   5L,
  "13/03/2020",   765L,             38L,              38L,   6L,
  "14/03/2020",   762L,             50L,              50L,   7L,
  "15/03/2020",  1241L,            103L,             103L,   1L,
  "16/03/2020",  1620L,            129L,             129L,   2L,
  "17/03/2020",  1734L,            152L,             152L,   3L,
  "18/03/2020",  2291L,            211L,             211L,   4L,
  "19/03/2020",  2498L,            205L,             205L,   5L,
  "20/03/2020",  2040L,            217L,             217L,   6L,
  "21/03/2020",  1899L,            235L,             235L,   7L,
  "22/03/2020",  4240L,            392L,             392L,   1L,
  "23/03/2020",  4038L,            510L,             510L,   2L,
  "24/03/2020",  5340L,            471L,             471L,   3L,
  "25/03/2020",  6107L,            625L,             625L,   4L,
  "26/03/2020",  7219L,            652L,             652L,   5L,
  "27/03/2020",  6470L,            635L,             635L,   6L,
  "28/03/2020",  6369L,            568L,             568L,   7L,
  "29/03/2020",  5965L,            569L,             569L,   1L,
  "30/03/2020",  6935L,            763L,             763L,   2L
)

example_data$date <- as.Date(example_data$date, format = "%d/%m/%Y")

data <- example_data %>% 
  select(date, tests, positive_tests) %>% 
  pivot_longer(-date, names_to = "type", values_to = "value") %>%
  filter(type == "positive_tests")

slider::slide_period_dbl(data$value, data$date, .period = "week", .f = mean)
#> [1]  45.0000 104.0000 379.2857 637.4000

slider::slide_period(data, data$date, .period = "week", .f = ~.x)
#> [[1]]
#> # A tibble: 1 x 3
#>   date       type           value
#>   <date>     <chr>          <int>
#> 1 2020-03-11 positive_tests    45
#> 
#> [[2]]
#> # A tibble: 7 x 3
#>   date       type           value
#>   <date>     <chr>          <int>
#> 1 2020-03-12 positive_tests    45
#> 2 2020-03-13 positive_tests    38
#> 3 2020-03-14 positive_tests    50
#> 4 2020-03-15 positive_tests   103
#> 5 2020-03-16 positive_tests   129
#> 6 2020-03-17 positive_tests   152
#> 7 2020-03-18 positive_tests   211
#> 
#> [[3]]
#> # A tibble: 7 x 3
#>   date       type           value
#>   <date>     <chr>          <int>
#> 1 2020-03-19 positive_tests   205
#> 2 2020-03-20 positive_tests   217
#> 3 2020-03-21 positive_tests   235
#> 4 2020-03-22 positive_tests   392
#> 5 2020-03-23 positive_tests   510
#> 6 2020-03-24 positive_tests   471
#> 7 2020-03-25 positive_tests   625
#> 
#> [[4]]
#> # A tibble: 5 x 3
#>   date       type           value
#>   <date>     <chr>          <int>
#> 1 2020-03-26 positive_tests   652
#> 2 2020-03-27 positive_tests   635
#> 3 2020-03-28 positive_tests   568
#> 4 2020-03-29 positive_tests   569
#> 5 2020-03-30 positive_tests   763
```

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Were you looking for `slide_index_dbl()`? This always returns something with the same size as its input (so, good for `mutate()`), and this example looks backwards 3 days from the current date and forward 3 days from the current date. So with this regular series yes it is the same as `slide_dbl()`.

```r
example_data %>% 
  select(date, tests, positive_tests) %>% 
  pivot_longer(-date, names_to = "type", values_to = "value") %>% 
  group_by(type) %>%   
  mutate(
    value_ma = tsibble::slide_dbl(value, mean, na.rm = TRUE, .size = 7, .align = "center"),
    value_ma2 = slider::slide_dbl(value, mean, na.rm = TRUE, .before = 3, .after = 3, .complete = TRUE),
    value_ma3 = slider::slide_index_dbl(value, date, mean, na.rm = TRUE, .before = 3, .after = 3, .complete = TRUE)
  )
#> # A tibble: 40 x 6
#> # Groups:   type [2]
#>    date       type           value value_ma value_ma2 value_ma3
#>    <date>     <chr>          <int>    <dbl>     <dbl>     <dbl>
#>  1 2020-03-11 tests            388     NA        NA        NA  
#>  2 2020-03-11 positive_tests    45     NA        NA        NA  
#>  3 2020-03-12 tests            666     NA        NA        NA  
#>  4 2020-03-12 positive_tests    45     NA        NA        NA  
#>  5 2020-03-13 tests            765     NA        NA        NA  
#>  6 2020-03-13 positive_tests    38     NA        NA        NA  
#>  7 2020-03-14 tests            762   1025.     1025.     1025. 
#>  8 2020-03-14 positive_tests    50     80.3      80.3      80.3
#>  9 2020-03-15 tests           1241   1297      1297      1297  
#> 10 2020-03-15 positive_tests   103    104       104       104  
```

**Comment by DavisVaughan** [comment]
FWIW I think that error is coming from dplyr, and might be a bug (normally you get a better error). I've reported that upstream https://github.com/tidyverse/dplyr/issues/5551

**Comment by akarlinsky** [comment]
Thank you, `slide_index_dbl` is indeed better suited. The reason I opted for `slide_period` was to specify "1 week" instead of using -3 and +3 on each side of `slide_dbl` or `slide_index_dbl`. In that regard `.size = 7, .align = "center"` of `tsibble::slide_dbl` was clearer in the flow from thought process to execution: I want a 7 day moving average so .size is 7, or "week".

**Comment by DavisVaughan** [comment]
Are you sure you want center alignment? It seems like you want `"right"` alignment. With center alignment you are looking "into the future" by 3 days to get the rolling moving average, which seems like cheating. From what you've said, it looks like you want the current day + 6 days before it included in your average, which would be right alignment. In slider you'd use `.before = 6` and leave `.after` as is.

I understand that parameterizing in terms of `.size` is clearer to some people. If you come from SQL and use window functions a lot, the before/after syntax maps perfectly. But if you use tsibble/zoo then it may be more difficult. The `size` + `align` parameterization is also less flexible, for example, there is no equivalent to `.before = 4, .after = 3`
