### ISSUE TITLE
Add a mini vignette on converting from tsibble

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/slider#128]
Probably just fake the tsibble code + results to avoid Suggest-ing it 

Many people have been rightly confused by this!
https://twitter.com/smwindecker/status/1323528673249513473?s=20

**Comment by Fuco1** [comment]
I'm especially confused about why I need to specify the index (variable, data?) as an input argument.  It is in the tsibble after all.

**Comment by DavisVaughan** [comment]
> It is in the tsibble after all.

Sure, but slider (purposefully) knows nothing about tsibble
