### ISSUE TITLE
pre-initializing slickr sliders behind tabsets

### ISSUE THREAD

**Issue by dan-reznik** [DavisVaughan/slider#69]
Consider the following rmarkdown excerpt

```{r}
library(slickR)
```
'# Section 1 {.tabset .tabset-fade .tabset-pills}

'## Subsection A {-}

```{r,chunk1}
slickR( imgs1, ... ) + settings( ... )
```
'## Subsection B {-}

```{r,chunk2}
slickR( imgs2, ... ) + settings( ... )
```

As it is well known, the slider in chunk2 will first render hidden, therefore, when the user selects that tab, the slider will appear empty (the desired behavior would be for it to appear with imgs2). This is a FAQ, but what do I need to do in a separate .css to intialize the hidden sliders?

For a live example do check out this [page](https://dan-reznik.github.io/Elliptical-Billiards-Triangular-Orbits/envelopes1618.html). Under "Envelope Carousels" check the 2nd tab called "X(2) Barycenter" and notice the slider appears empty.

**Comment by DavisVaughan** [comment]
Did you happen to open this on the wrong repo?
