### ISSUE TITLE
Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'character'

### ISSUE THREAD

**Issue by Malichot** [DavisVaughan/slider#82]
Hello all,

First of all, thank you very much for developing this package ! I'm encountering an error I don't seem to understand ; it was actually working two days ago, I don't know why it's not today...

In a dataframe that looks like this :

```
> corpus_spec[1:20,2]

# A tibble: 20 x 1
   mots 
   <chr>
 1 ADJ  
 2 NC   
 3 NP   
 4 !    
 5 un   
 6 NC   
 7 !    
 8 ADV  
 9 trop 
10 ADJ  
11 ADV  
12 trop 
13 ADJ  
14 .    
15 puis 
16 NC   
17 ADJ  
18 !    
19 NP   
20 NC`
```

I try to run the following code :

```
corpus_spec <- corpus_spec %>%
     mutate(motifs = slide_chr(mots, paste, collapse = " ", .after = 4)) %>%
     head(-4)
```

And I get the following error in terminal : 

> Error in FUN(X[[i]], ...) : 
>   Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'character'

Thanks a lot in advance !!

**Comment by DavisVaughan** [comment]
It works for on with the cran version of slider (and the cran version of vctrs, which is the other important package at play here)

```r
library(slider)

slide_chr(letters, paste, collapse = " ", .after = 4)
#>  [1] "a b c d e" "b c d e f" "c d e f g" "d e f g h" "e f g h i" "f g h i j"
#>  [7] "g h i j k" "h i j k l" "i j k l m" "j k l m n" "k l m n o" "l m n o p"
#> [13] "m n o p q" "n o p q r" "o p q r s" "p q r s t" "q r s t u" "r s t u v"
#> [19] "s t u v w" "t u v w x" "u v w x y" "v w x y z" "w x y z"   "x y z"    
#> [25] "y z"       "z"
```

**Comment by DavisVaughan** [comment]
I also just tried with the dev versions of slider, vctrs, rlang, and dplyr and it still works so I'm not sure what is going on for you.

Can you post your session info please?

**Comment by Malichot** [comment]
Thanks a lot for your prompt answer !! Here's my sessionInfo : 

> > sessionInfo()
> R version 3.4.4 (2018-03-15)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.4 LTS
> 
> Matrix products: default
> BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
> 
> locale:
>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
>  [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] vctrs_0.2.4       ggfortify_0.4.8   kohonen_3.0.10    slider_0.1.2      data.table_1.12.8 reshape2_1.4.3    ggsci_2.9        
>  [8] cluster_2.0.6     factoextra_1.0.6  FactoMineR_1.41   forcats_0.4.0     stringr_1.4.0     purrr_0.3.3       readr_1.3.1      
> [15] tidyr_1.0.0       tibble_2.1.3      ggplot2_3.2.1     tidyverse_1.3.0   dplyr_0.8.3       tidytext_0.2.2   
> 
> loaded via a namespace (and not attached):
>  [1] ggrepel_0.8.1        Rcpp_1.0.4           lubridate_1.7.4      lattice_0.20-35      assertthat_0.2.1     R6_2.4.1            
>  [7] cellranger_1.1.0     plyr_1.8.5           backports_1.1.5      reprex_0.3.0         httr_1.4.1           pillar_1.4.3        
> [13] rlang_0.4.5          lazyeval_0.2.2       readxl_1.3.1         rstudioapi_0.11      Matrix_1.2-12        munsell_0.5.0       
> [19] broom_0.5.3          compiler_3.4.4       janeaustenr_0.1.5    modelr_0.1.5         pkgconfig_2.0.3      flashClust_1.01-2   
> [25] tidyselect_1.0.0     gridExtra_2.3        fansi_0.4.1          crayon_1.3.4         dbplyr_1.4.2         withr_2.1.2         
> [31] MASS_7.3-49          leaps_3.1            SnowballC_0.6.0      grid_3.4.4           nlme_3.1-131         jsonlite_1.6.1      
> [37] gtable_0.3.0         lifecycle_0.1.0      DBI_1.1.0            magrittr_1.5         scales_1.1.0         tokenizers_0.2.1    
> [43] warp_0.1.0           cli_2.0.1            stringi_1.4.5        fs_1.3.1             scatterplot3d_0.3-41 xml2_1.2.2          
> [49] generics_0.0.2       tools_3.4.4          glue_1.3.2           hms_0.5.3            yaml_2.2.1           colorspace_1.4-1    
> [55] rvest_0.3.5          haven_2.2.0

A strange thing happens ; I tried to insert the vctrs library and it seems to be working if I rerun the package vctrs before applying the function...

**Comment by DavisVaughan** [comment]
Does my example fail for you?

If it does not fail for you, can you please provide me a reproducible example of what fails for you? The code you have provided at the top is not reproducible (i.e. I don't know what `corpus_spec` is created from). Please use the reprex package for this if you can: https://reprex.tidyverse.org/#usage

**Comment by DavisVaughan** [comment]
If you haven't restarted R / RStudio in awhile, I would try that too

**Comment by Malichot** [comment]
Dear Davis,

Seems to be working indeed when I restarted RStudio. I had the head inside and forget to do that before. Thanks a lot for your time and all the best !
